[server]
headless = true
address = "0.0.0.0"
enableCORS = true
enableXsrfProtection = true
xsrfCookieSameSite = "none"
maxUploadSize = 200
fileWatcherType = "none"

[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "dark"
primaryColor = "#8a7fff"
